apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==  # base64 encoded value of "root"
  mysql-database: cGZl           # base64 encoded value of "pfe"
  mysql-user: ZGF0YWJhc2VfdXNlcg==  # base64 encoded value of "database_user" (change to your non-root user)
  mysql-password: ZGF0YWJhc2VfcGFzc3dvcmQ=  # base64 encoded value of "database_password" (change to your non-root password)
