apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==  # base64 encoded value of "root"
  mysql-database: cGZl           # base64 encoded value of "pfe"
  mysql-user: cm9vdA==           # base64 encoded value of "root"
  mysql-password: cm9vdA==       # base64 encoded value of "root"
